#!/usr/bin/env python3
import os
import shutil
from datetime import datetime
from pathlib import Path

from docx import Document


def resolve_doc_path() -> Path:
    env_doc = os.environ.get("MANUSCRIPT_DOC")
    if env_doc:
        return Path(env_doc)
    return Path("paper/SAB_HET_2.1_JU.docx")


DOC = resolve_doc_path()


def main() -> None:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup = DOC.with_name(f"{DOC.stem}.backup_{stamp}.docx")
    shutil.copy2(DOC, backup)

    replacements = {
        "Even with perfect classification, based on effect sizes on 84-day mortality seen for adjunctive rifampicin, post-hoc analyses required very large trials (often >20,000 participants) to achieve adequate power for most subphenotypes. Decreasing classification accuracy markedly reduced power, increased type 1 error, and introduced bias. Enrichment strategies were unsuccessful due to extreme screening requirements. Ordinal outcomes dramatically increased statistical power when correctly specified but performed worse when misspecified. Under misclassification, ordinal models also produced less biased estimates than binary models of the same treatment effect, because pooling information across multiple outcome thresholds reduces susceptibility to non-collapsible bias at extreme event rates.": (
            "Even with perfect classification, post-hoc detection of heterogeneous treatment effects remained highly conditional on subphenotype prevalence, baseline mortality, and effect size. Subphenotype B was readily detectable at moderate sample sizes, whereas C and D remained challenging and E remained difficult under binary mortality analyses alone. Decreasing classification accuracy reduced power, increased type I error, and introduced bias. Enrichment appeared realistic for subphenotype B but remained unattractive for most other subphenotypes. Ordinal outcomes substantially improved performance when they matched the treatment-effect structure, but this depended on both the assumed mechanism and the number of ordinal levels used."
        ),
        "Detecting HTE in SAB is challenging, demanding extremely large trials and highly accurate subphenotype classification. To advance stratified medicine in SAB, research should prioritize developing robust classifiers (sensitivity and specificity >95%) and use statistically efficient outcomes and trial designs. Outcomes must be matched to plausible effects of interventions: one outcome may not be the best for all approaches.": (
            "Detecting HTE in SAB is challenging, but not uniformly infeasible. Feasibility depends on the interaction between subphenotype frequency, baseline risk, classifier performance, and outcome choice. To advance stratified medicine in SAB, research should prioritize robust classifiers, mechanism-matched outcomes, and trial designs that acknowledge uncertainty in subgroup prevalence and treatment-effect structure."
        ),
        "The statistical power for detecting subphenotype-specific treatment effects in a standard two-arm RCT, assuming perfect classification and the effects seen in the recent SAB analysis, was highly dependent on the subphenotypes prevalence, baseline event rate, and the magnitude of the true odds ratio (OR). The results, summarized in Table 3 and Figure 1, demonstrate that substantial total trial sizes are necessary to achieve 80% power in post-hoc analyses, and that only subphenotype B (with an extremely large effect) was possible at reasonable sample sizes (<5,000). As expected in a traditional two-arm RCT, Type 1 error was well calibrated and bias was minimal. At 100% classification accuracy, power for subgroup B rose from ~0 (n=500) to 0.70 (n=5,000), 0.97 (n=10,000), however, at n=20,000 power remained below 50% for C (0.25), D (0.444), and E (0.456).": (
            "The statistical power for detecting subphenotype-specific treatment effects in a standard two-arm RCT, assuming perfect classification and the conservatively shrunk effects used here, was highly dependent on subphenotype prevalence, baseline event rate, and effect size. The results, summarized in Table 3 and Figure 1, show that subphenotype B was readily detectable at realistic sample sizes, reaching essentially complete power by n=5,000. In contrast, C and D remained only modestly powered even at larger sample sizes, and E remained difficult under binary mortality analyses despite becoming clearly more plausible than in earlier iterations of the simulation. As expected in a traditional two-arm RCT, Type I error was well calibrated and bias was minimal."
        ),
        "We evaluated the impact of five hypothetical diagnostic tests ranging from mediocre to near-perfect accuracy on the number needed to screen (NNS) and number needed to randomize (NNR). For subphenotype B, which has a large treatment effect (OR 4.3) and moderate frequency (13%), enrichment remains feasible even with imperfect tests: NNS ranges from ~7,000 with a near-perfect test (99%/99%) to ~2,800 with a balanced test (80%/80%), with corresponding NNR values of ~140-800 participants (Figure 3 for NNS and NNR). Importantly, and as expected, biased estimates were still present. However, for all other subphenotypes, enrichment is not a feasible strategy even with excellent classifiers. Type I error in the null subgroup (A) remained close to nominal in the main simulation (n=20,000), ranging from 4.7% at 100% accuracy to 5.9% at 70% accuracy.": (
            "We evaluated the impact of five hypothetical diagnostic tests ranging from mediocre to near-perfect accuracy on the number needed to screen (NNS) and number needed to randomize (NNR). For subphenotype B, which combines a large treatment effect (OR 4.3 after shrinkage) with moderate frequency (13%), enrichment remained realistic: NNS ranged from about 1,100 with a near-perfect test (99%/99%) to about 3,300 with a balanced test (80%/80%), with corresponding NNR values of roughly 140 to 930 participants (Figure 3 for NNS and NNR). Biased estimates were still present, as expected. In contrast, for the other subphenotypes enrichment remained unattractive or infeasible even with excellent classifiers. Type I error in the null subgroup (A) remained close to nominal in the main simulation (n=20,000), ranging from 4.7% at 100% accuracy to 5.9% at 70% accuracy."
        ),
        "These results clearly show the strengths and weaknesses of ordinal outcomes: when they correctly reflect the treatment effect, they are dramatically more powerful; and surprisingly, less biased. However, if mis-specified, they make the situation much worse.": (
            "These results show the strengths and tradeoffs of ordinal outcomes. When the ordinal structure reasonably reflects the treatment effect, they can be much more powerful and less biased than binary mortality analyses. When the effect is concentrated mainly at death, binary analysis remains preferable, but the degree of ordinal underperformance depends on how the ordinal scale is constructed. In particular, our 6-point main analysis performed slightly better under proportional-odds scenarios, whereas the 5-point sensitivity analysis was somewhat more robust under death-only non-proportional scenarios."
        ),
        "Even with perfect classification and conservatively shrunk effect sizes, the required sample sizes for most subphenotypes far exceeded those of any ongoing or planned SAB trial. Only subphenotype B - with a large effect and moderate prevalence - was detectable at realistic sample sizes, and this relied on an effect that, even after shrinkage, remains unusually large. Critically, subphenotype prevalence and mortality varied substantially across the published cohorts we examined, producing more than ten-fold variation in required sample size for the same subphenotype. This makes a priori sample size estimation for subphenotype-specific effects extremely unreliable, as the distribution of subphenotypes in a planned trial is unlikely to match that of any single historical cohort. Adaptive designs, such as Bayesian platform approaches with information-borrowing may therefore be preferable to fixed designs predicated on a single assumed prevalence.": (
            "Even with perfect classification and conservatively shrunk effect sizes, required sample sizes remained large for most subphenotypes. Subphenotype B, however, was clearly detectable at realistic sample sizes, whereas C and D remained difficult and E remained strongly dependent on outcome choice. Critically, subphenotype prevalence and mortality varied substantially across the published cohorts we examined, producing marked variation in required sample size for the same subphenotype. This makes a priori sample size estimation for subphenotype-specific effects unreliable, as the distribution of subphenotypes in a planned trial is unlikely to match that of any single historical cohort. Adaptive designs, such as Bayesian platform approaches with information-borrowing, may therefore be preferable to fixed designs predicated on a single assumed prevalence."
        ),
        "Enrichment strategies, in which only patients classified into a target subphenotype are randomised, reduced the number needed to randomise but did not resolve bias and imposed screening burdens that were infeasible for most subphenotypes. Only subphenotype B, with its combination of large effect, moderate prevalence, and distinctive clinical features, remained a plausible enrichment target. For all other subphenotypes, even near-perfect classifiers produced prohibitive screening requirements. This is a sobering finding for those hoping that enrichment alone could rescue underpowered subphenotype analyses.": (
            "Enrichment strategies, in which only patients classified into a target subphenotype are randomised, reduced the number needed to randomise but did not resolve bias and imposed screening burdens that remained substantial for most subphenotypes. Subphenotype B, with its combination of large effect and moderate prevalence, remained a plausible enrichment target. For the remaining subphenotypes, even near-perfect classifiers produced screening requirements that were still difficult to justify. Enrichment therefore looks useful in selected settings rather than as a general solution to underpowered subphenotype analyses."
        ),
        "Crucially, this advantage only holds when the proportional odds assumption is approximately correct. When the treatment effect was concentrated at a single threshold (our death-only simulation), the ordinal model diluted a real signal with noise from uninformative thresholds and performed substantially worse than binary analysis. This finding has direct and important implications for outcome selection.": (
            "Crucially, this advantage only holds when the proportional-odds assumption is approximately correct. When the treatment effect was concentrated mainly at death (our death-only simulation), the ordinal model diluted part of the signal with uninformative thresholds and binary analysis remained superior. The magnitude of this penalty was not fixed, however, and depended in part on the number of outcome levels used: adding levels improved efficiency under proportional-odds scenarios but could reduce robustness under death-only non-proportional scenarios. This has direct implications for outcome selection."
        ),
        "The implications for SAB are substantial. Different interventions under consideration plausibly act through different mechanisms. Adjunctive antibiotics such as rifampicin or fosfomycin are hypothesised to improve bacterial clearance, which might manifest across the outcome spectrum - fewer complications, shorter hospital stays, and reduced mortality - making ordinal outcomes well suited. Source control interventions such as surgery for endocarditis act on a specific anatomical problem, where the relevant outcome may be prevention of a defined complication rather than a graded improvement. Host-directed therapies might primarily affect the most severely ill, with effects concentrated at the mortality threshold. When subphenotypes are added to this picture, the complexity increases further: the same intervention might plausibly act differently across subphenotypes. In subphenotype B, with very low baseline mortality, the clinically relevant endpoint might be duration of bacteraemia or catheter-related complications rather than death, while in higher-severity subphenotypes mortality may be the most informative measure. A well-designed platform trial in SAB might therefore need to pre-specify different primary outcomes for different interventionsubphenotype combinations - an approach that is methodologically coherent but presents obvious challenges for interpretation and regulatory acceptance.": (
            "The implications for SAB are substantial. Different interventions under consideration plausibly act through different mechanisms. Adjunctive antibiotics such as rifampicin or fosfomycin are hypothesised to improve bacterial clearance, which might manifest across the outcome spectrum - fewer complications, shorter hospital stays, and reduced mortality - making ordinal outcomes well suited. Source control interventions such as surgery for endocarditis act on a specific anatomical problem, where the relevant outcome may be prevention of a defined complication rather than a graded improvement. Host-directed therapies might primarily affect the most severely ill, with effects concentrated at the mortality threshold. When subphenotypes are added to this picture, the complexity increases further: the same intervention might plausibly act differently across subphenotypes. In subphenotype B, despite only modest baseline mortality, the clinically relevant endpoint might still include complications or trajectory rather than death alone, whereas in higher-severity subphenotypes mortality may remain the most informative measure. A well-designed platform trial in SAB might therefore need to pre-specify different primary outcomes for different intervention-subphenotype combinations - an approach that is methodologically coherent but presents obvious challenges for interpretation and regulatory acceptance."
        ),
    }

    d = Document(str(DOC))
    changed = 0
    for p in d.paragraphs:
        txt = (p.text or "").strip()
        if txt in replacements:
            p.text = replacements[txt]
            changed += 1

    d.save(str(DOC))
    print(f"Updated paragraphs: {changed}")
    print(f"Backup: {backup}")


if __name__ == "__main__":
    main()
